### PR TITLE
Updates nan version to ^2.3.2

### PR DESCRIPTION
**Pull request by chadwatson**
This change updates `lwip` to the latest version of `nan` in order to fix an issue with node v6 (#249).

`nan` v2.0.9 uses v8 methods which are no longer available in node6. [Version 2.2.0 fixed this issue](https://github.com/nodejs/nan/commit/3603435109f981606d300eb88004ca101283acec), so now those methods are only utilized for older versions of node.

All tests pass and the build successfully works in node v6.0.0 on Mac OS X 10.11.4.

### CODE REVIEW

**Comment by jmunsch** [comment]
Just putting the compile error here for anyone else who runs into this issue:


  ```
CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
```

**Comment by jeaye** [comment]
Any update on this?

**Comment by AckerApple** [comment]
@chadwatson, thank you so much for creating this branch that fixes the problem. I needed it fairly badly. Below, incase it saves anyone else an extra second, is the change you will need to make to your package.json file (until a fix has been released on the master branch):

//FROM
"dependencies": {
  "lwip": "0.0.8"
}


//INTO
"dependencies": {
  "lwip": "git://github.com/chadwatson/lwip.git#fix-node6"
}

**Comment by EyalAr** [comment]
thanks @chadwatson
