### ISSUE TITLE
lwip fails to install

### ISSUE THREAD

**Issue by kuba12kozak** [EyalAr/lwip#211]
Hi,
I have following errors while installing lwip:

> lwip@0.0.8 install /root/aplikacja/node_modules/lwip
> node-gyp rebuild
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-22-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/aplikacja/node_modules/lwip
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.8 install script.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-22-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "lwip"
npm ERR! cwd /root/aplikacja
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/aplikacja/npm-debug.log
npm ERR! not ok code 0

I'm not able to figgure out the reason of this errors. Any help is apprecited. Thanks

**Comment by kuba12kozak** [comment]
Nevermind, I updated node to v.4.2.2 and it works :)

**Comment by meticulo3366** [comment]
does not work on ubuntu with node 4.2.2

s4_1 | Error: Cannot find module '../build/Release/lwip_image'
s4_1 | at Function.Module._resolveFilename (module.js:337:15)
s4_1 | at Function.Module._load (module.js:287:25)
s4_1 | at Module.require (module.js:366:17)
s4_1 | at require (module.js:385:17)
s4_1 | at /code/node_modules/indico.io/node_modules/lwip/lib/Image.js:3:22
s4_1 | at Object. (/code/node_modules/indico.io/node_modules/lwip/lib/Image.js:16:3)
s4_1 | at Module._compile (module.js:435:26)
s4_1 | at Object.Module._extensions..js (module.js:442:10)
s4_1 | at Module.load (module.js:356:32)
s4_1 | at Function.Module._load (module.js:311:12)
s4_1 | at Module.require (module.js:366:17)
s4_1 | at require (module.js:385:17)
s4_1 | at /code/node_modules/indico.io/node_modules/lwip/lib/ImagePrototypeInit.js:3:17
s4_1 | at Object. (/code/node_modules/indico.io/node_modules/lwip/lib/ImagePrototypeInit.js:620:3)
s4_1 | at Module._compile (module.js:435:26)
s4_1 | at Object.Module._extensions..js (module.js:442:10)
s4_1 | at Module.load (module.js:356:32)
s4_1 | at Function.Module._load (module.js:311:12)
s4_1 | at Module.require (module.js:366:17)
s4_1 | at require (module.js:385:17)
s4_1 | at Object. (/code/node_modules/indico.io/node_modules/lwip/index.js:1:63)
s4_1 | at Module._compile (module.js:435:26)
s4_1 | at Object.Module._extensions..js (module.js:442:10)
s4_1 | at Module.load (module.js:356:32)
s4_1 | at Function.Module._load (module.js:311:12)
s4_1 | at Module.require (module.js:366:17)
s4_1 | at require (module.js:385:17)
s4_1 | at Object. (/code/node_modules/indico.io/lib/image.js:1:74)

package.json below...

{
"name": "indico.io",
"description": "A Node.js wrapper for the Indico’s API",
"version": "0.4.6",
"homepage": "https://github.com/IndicoDataSolutions/IndicoIo-node",
"author": {
"name": "Joseph Núñez",
"email": "toctochello@gmail.com"
},
"contributors": [
{
"name": "Madison May",
"email": "madison@indico.io"
}
],
"keywords": [],
"repository": {
"type": "git",
"url": "git://github.com/IndicoDataSolutions/IndicoIo-node.git"
},
"bugs": {
"url": "https://github.com/IndicoDataSolutions/IndicoIo-node/issues"
},
"licenses": [
{
"type": "MIT",
"url": "https://github.com/IndicoDataSolutions/IndicoIo-node/blob/master/LICENSE"
}
],
"main": "./lib/indico",
"dependencies": {
"bluebird": "^2.9.24",
"config-ini": "^0.2.2",
"expand-tilde": "^1.2.0",
"file-type": "^2.11.0",
"lwip": "0.0.8",
"request": "^2.36.0",
"valid-url": "^1.0.9"
},
"devDependencies": {
"should": "~3.0.1",
"mocha": "~1.17.0",
"chai": "1.9.1"
},
"scripts": {
"test": "mocha test/.js test/integration/.js"
},
"js-flags": "--harmony",
"_id": "indico.io@0.4.6",
"_shasum": "f6fb1d899427bfe50803b9580b1f8d89935c73be",
"_resolved": "https://registry.npmjs.org/indico.io/-/indico.io-0.4.6.tgz",
"_from": "indico.io@>=0.4.6 <0.5.0",
"_npmVersion": "2.11.2",
"_nodeVersion": "4.2.0",
"_npmUser": {
"name": "madisonmay",
"email": "madison@indico.io"
},
"dist": {
"shasum": "f6fb1d899427bfe50803b9580b1f8d89935c73be",
"tarball": "http://registry.npmjs.org/indico.io/-/indico.io-0.4.6.tgz"
},
"maintainers": [
{
"name": "slatervictoroff",
"email": "slater@indico.io"
},
{
"name": "madisonmay",
"email": "madison@indico.io"
},
{
"name": "indicodatasolutions",
"email": "contact@indico.io"
}
],
"directories": {}
}
